name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Every day at midnight UTC
  workflow_dispatch:     # Allow manual trigger

permissions:
  contents: write         # 👈 REQUIRED to push to branches!

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate the snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: dilukaathukorala
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
